[tox]
env_list = lint, py{310,311,312,313}, test
minversion = 4.10.0
requires =
    tox-uv>=1.16.0

[testenv]
runner = uv-venv-lock-runner
package = wheel
wheel_build_env = .pkg
dependency_groups =
    dev
commands =
    pytest --cov=awsmp

[testenv:test]
description = run the tests with pytest
commands =
    pytest --cov=awsmp

[testenv:lint]
description = run linter
commands =
    isort --check .
    black --check .
    mypy . --check-untyped-defs

[testenv:fix]
description = run formatters
commands =
    isort .
    black .
