CATEGORIES = [
    "Backup & Recovery",
    "Data Analytics",
    "High Performance Computing",
    "Migration",
    "Network Infrastructure",
    "Operating Systems",
    "Security",
    "Storage",
    "Agile Lifecycle Management",
    "Application Development",
    "Application Servers",
    "Application Stacks",
    "Continuous Integration and Continuous Delivery",
    "Infrastructure as Code",
    "Issue & Bug Tracking",
    "Monitoring",
    "Log Analysis",
    "Source Control",
    "Testing",
    "Blockchain",
    "Collaboration & Productivity",
    "Contact Center",
    "Content Management",
    "CRM",
    "eCommerce",
    "eLearning",
    "Human Resources",
    "IT Business Management",
    "Project Management",
    "Human Review Services",
    "ML Solutions",
    "Data Labeling Services",
    "Computer Vision",
    "Natural Language Processing",
    "Speech Recognition",
    "Text",
    "Image",
    "Video",
    "Audio",
    "Structured",
    "Intelligent Automation",
    "Financial Services Data",
    "Healthcare & Life Sciences Data",
    "Media & Entertainment Data",
    "Telecommunications Data",
    "Gaming Data",
    "Automotive Data",
    "Manufacturing Data",
    "Resources Data",
    "Retail, Location & Marketing Data",
    "Public Sector Data",
    "Environmental Data",
    "Analytics",
    "Applications",
    "Device Connectivity",
    "Device Management",
    "Device Security",
    "Industrial IoT",
    "Smart Home & City",
    "Assessments",
    "Implementation",
    "Managed Services",
    "Premium Support",
    "Training",
    "Education & Research",
    "Financial Services",
    "Healthcare & Life Sciences",
    "Media & Entertainment",
    "Industrial",
    "Energy",
]
