name: testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: |
          # FIXME: not pining to an exact version results in getting poetry 1.0.10 which doesn't work
          pip3 install tox poetry==1.7.1
          poetry --version
      - uses: actions/checkout@v5
      - name: Run tox
        run: tox
  snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: snapcore/action-build@v1
